---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: secrets
  labels:
    {{- include "trivy-runner.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
    helm.sh/hook-weight: "10"
type: Opaque
stringData:
  # == RUNTIME SERVICES ==
  # - REGISTRY USER
  registry-user: "{{ .Values.secrets.registryUser }}"
  # - REGISTRY PASSWORD
  registry-password: "{{ .Values.secrets.registryPassword }}"
  # - SENTRY FOR TRIVY
  sentry-dsn: "{{ .Values.secrets.sentryDsn }}"

