{{- if .Values.serviceAccount.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-sa
  labels:
    {{- include "trivy-runner.labels" . | nindent 4 }}
{{- end -}}
