{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "trivy-runner.namespace" . }}
  name: {{ include "trivy-runner.serviceAccountName" . }}
  labels:
    {{- include "trivy-runner.labels" . | nindent 4 }}
{{- end -}}
